# Some config of the topology
# OPOT_CONTROLLER_IP = "10.0.0.7"
# OPOT_CONTROLLER_PORT = 42582
# NODE_CONTROLLER_PORT = 44000

# Size of the OPoT info exchanged between the OPoT Packets
CML_SIZE = 8
SECRET_SIZE = 4
SIZE_OF_CML_AND_SECRET = CML_SIZE + SECRET_SIZE
SEQUENCE_SIZE = 4
SIZE_OF_OPOT_INFO = SIZE_OF_CML_AND_SECRET  # + SEQUENCE_SIZE

